### ISSUE TITLE
binascii.Error: Invalid base64-encoded string: number of data characters

### ISSUE THREAD

**Issue by burjuyz** [AsmSafone/RadioPlayerV3#28]
Any chance to start the bot?

`ubuntu@azura:~/RadioPlayerV3$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    from utils import mp, USERNAME, FFMPEG_PROCESSES
  File "/home/ubuntu/RadioPlayerV3/utils.py", line 57, in <module>
    from user import USER
  File "/home/ubuntu/RadioPlayerV3/user.py", line 37, in <module>
    USER.start()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 52, in start
    is_authorized = await self.connect()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect
    await self.load_session()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/client.py", line 674, in load_session
    await self.storage.open()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/storage/memory_storage.py", line 41, in open
    base64.urlsafe_b64decode(
  File "/usr/lib/python3.8/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/lib/python3.8/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (373) cannot be 1 more than a multiple of 4
`

**Comment by AsmSafone** [comment]
> Any chance to start the bot?
> 
> `ubuntu@azura:~/RadioPlayerV3$ python3 main.py Traceback (most recent call last): File "main.py", line 28, in <module> from utils import mp, USERNAME, FFMPEG_PROCESSES File "/home/ubuntu/RadioPlayerV3/utils.py", line 57, in <module> from user import USER File "/home/ubuntu/RadioPlayerV3/user.py", line 37, in <module> USER.start() File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap return loop.run_until_complete(coroutine) File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete return future.result() File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 52, in start is_authorized = await self.connect() File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect await self.load_session() File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/client.py", line 674, in load_session await self.storage.open() File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/storage/memory_storage.py", line 41, in open base64.urlsafe_b64decode( File "/usr/lib/python3.8/base64.py", line 133, in urlsafe_b64decode return b64decode(s) File "/usr/lib/python3.8/base64.py", line 87, in b64decode return binascii.a2b_base64(s) binascii.Error: Invalid base64-encoded string: number of data characters (373) cannot be 1 more than a multiple of 4 `

upgrade your python version to 3.9 or later.

**Comment by burjuyz** [comment]
I've updated and still no luck! 

`ubuntu@orbot:~/RadioPlayerV3$ python3 main.py
Traceback (most recent call last):
  File "/home/ubuntu/RadioPlayerV3/main.py", line 28, in <module>
    from utils import mp, USERNAME, FFMPEG_PROCESSES
  File "/home/ubuntu/RadioPlayerV3/utils.py", line 57, in <module>
    from user import USER
  File "/home/ubuntu/RadioPlayerV3/user.py", line 37, in <module>
    USER.start()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 52, in start
    is_authorized = await self.connect()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect
    await self.load_session()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyrogram/client.py", line 674, in load_session
    await self.storage.open()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyrogram/storage/memory_storage.py", line 41, in open
    base64.urlsafe_b64decode(
  File "/usr/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (373) cannot be 1 more than a multiple of 4
`
