### ISSUE TITLE
GroupCallNotFoundError

### ISSUE THREAD

**Issue by tapatianbeast** [AsmSafone/RadioPlayerV3#5]
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    from utils import mp, USERNAME, FFMPEG_PROCESSES
  File "/root/RadioPlayerV3/utils.py", line 28, in <module>
    from pytgcalls.exceptions import GroupCallNotFoundError
ImportError: cannot import name 'GroupCallNotFoundError'

Python 3.6

**Comment by deulizealand** [comment]
did you install it's requirement and fill needed config ?

note : check session string that you use.

**Comment by tapatianbeast** [comment]
API_ID=xxxxxxxxxxxxxxc
API_HASH=xxxxxxxxxxxxxxxx
STREAM_URL=http://stream.zeno.fm/xxxxxxxxxxx
BOT_TOKEN=1999514401:AAxxxxxxxxxxxxxxxxxxxxxxx
CHAT=-100151xxxxxxxcx
LOG_GROUP=
REPLY_MESSAGE=
ADMINS=1857xxxxxxxx
ADMIN_ONLY=
SESSION_STRING=
MAXIMUM_DURATION=600

The string bot is down
